permalink: date

# Setup
title: '开发笔记'
tagline: 'DevNotes'
description: 'Java程序员的开发笔记'
url: 'https://vivisidea.github.io'
baseurl: ''
paginate: 5

# About/contact
author: 
name: '小强'
url: 'https://vivisidea.github.io'
email: 

#Customvars
version: '1.0.0'

#highlighter: pygments
lsi: false
safe: false
excerpt_separator: ""

# Gems
gems: [jekyll-paginate]

markdown: kramdown
